services:
  sybil:
    build:
      context: ./Sybil
      dockerfile: Dockerfile
    networks:
      - moobbot

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - moobbot
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - path: ./backend/.env
    environment:
      - MONGO_DB_URI=mongodb://database:27017/dicom
      - SYBIL_MODEL_BASE_URL=http://sybil:5000
    depends_on:
      - sybil
      - database
    volumes:
      - dicom-uploads:/app/src/data/dicom/uploads
      - dicom-results:/app/src/data/dicom/results
      - report:/app/src/data/dicom/gen
    networks:
      - moobbot

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: ./frontend/.env
    depends_on:
      - backend
    networks:
      - moobbot
  
networks:
  moobbot:
    driver: bridge

volumes:
  mongo-data:
  dicom-uploads:
  dicom-results:
  report: